# Site settings
title: Oskar Emilsson
email: oskaremilsson@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Front End Developer.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
twitter_username: oskaremilsson
github_username:  oskaremilsson
screenshot: http://oskaremilsson.github.io/files/images/screenshot.jpg

# Build settings
markdown: kramdown

collections:
  courses:
    output: true
  projects:
    output: true
